language: python
python:
  - "3.4"
before_install:
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip

branches:
  only:
    - master
    - desenvolvimento
install:
  - pip install -r requirements.txt
script: 
  - python sipac/manage.py test
  - nosetests

after_script:
 - ./sonar-runner-2.4/bin/sonar-runner
